# Generated by Django 6.0.3 on 2026-04-14 20:24

from django.db import migrations, models


def sync_completed_from_status(apps, schema_editor):
    Session = apps.get_model('study_sessions', 'Session')
    Session.objects.filter(status='completed').update(completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(sync_completed_from_status, migrations.RunPython.noop),
    ]
