# Generated by Django 6.0.4 on 2026-05-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_session_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
