# Generated by Django 6.0.2 on 2026-05-01

from django.db import migrations, models


def add_course_pdf_text(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    table_name = Subject._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        ]

    if 'course_pdf_text' in columns:
        return

    field = models.TextField(blank=True, default="")
    field.set_attributes_from_name('course_pdf_text')
    schema_editor.add_field(Subject, field)


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_course_pdf_text, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='subject',
                    name='course_pdf_text',
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
    ]
