# Generated by Django 6.0.4 on 2026-05-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_course_pdf_subject_course_pdf_text'),
        ('subjects', '0002_subject_course_pdf_text'),
    ]

    operations = [
    ]
